[package]
name = "app-review-gate"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
serde = "1.0.186"
serde_json = "1.0.105"
shuttle-axum = "0.24.0"
shuttle-runtime = "0.24.0"
tokio = "1.28.2"
