name: Test_gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test_gate_environment
    steps:
      - run: echo "hey"

